export const PANEL_BACKGROUND_DARK = '#1F1F1F';
export const PANEL_FOREGROUND_DARK = '#CCCCCC';
export const EXPLORER_BACKGROUND_DARK = '#2D2D2D';
export const EXPLORER_FOREGROUND_DARK = PANEL_FOREGROUND_DARK;
export const SECTION_HEADER_BACKGROUND_DARK = '#767676';
export const SECTION_HEADER_FOREGROUND_DARK = '#FFFFFF';

export const BLACK_1 = '#2B2B2B';
export const GRAY_1 = '#CCCCCC';
